export const FETCH_TAKE_ME_ASSETS = "FETCH_TAKE_ME_ASSETS";

export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";
export const START_FETCHING_CATEGORIES = "START_FETCHING_CATEGORIES";
export const END_FETCHING_CATEGORIES = "END_FETCHING_CATEGORIES";
export const FETCH_CATEGORY_PRODUCTS = "FETCH_CATEGORY_PRODUCTS";
export const START_FETCHING_PRODUCTS = "START_FETCHING_PRODUCTS";
export const END_FETCHING_PRODUCTS = "END_FETCHING_PRODUCTS";
export const CHANGE_CURRENT_ID = "CHANGE_CURRENT_ID";
export const CHANGE_SLIDER_VALUE = "CHANGE_SLIDER_VALUE";
export const CHANGE_LAN_SUCCESS = "CHANGE_LAN_SUCCESS";
export const ERROR_ACTIVE = "ERROR_ACTIVE";
export const ERROR_INACTIVE = 'ERROR_INACTIVE';
export const INCREASE_PAGE_NUMBER = "INCREASE_PAGE_NUMBER";
export const RESET_PAGE_NUMBER = "RESET_PAGE_NUMBER";