export const FETCH_TAKE_ME_ASSETS = "FETCH_TAKE_ME_ASSETS";

export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const START_FETCHING_CATEGORIES = "START_FETCHING_CATEGORIES";
export const END_FETCHING_CATEGORIES = "END_FETCHING_CATEGORIES";